[package]
name = "ruhttps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sozu = "0.12.0"
sozu-command-lib = "0.12.0"
sozu-lib = "0.12.0"
time = "0.3.12"